// POST endpoint for agentic loops — handles incoming chat messages and returns AI-generated responses
// Import NextRequest (typed request object) and NextResponse (typed response helper) from Next.js server utilities
import { NextRequest, NextResponse } from "next/server";
// Import the pre-configured Anthropic client instance from the shared lib module
import client from "@/lib/anthropic";


//---V1 BASIC SIMPLE USAGE----//
// Define and export an async POST handler — Next.js App Router automatically maps this to HTTP POST requests
// export async function POST(request: NextRequest) {
//     // Parse the incoming JSON body and destructure the `messages` array (chat history from the client)
//     const { messages } = await request.json();

//     try {
//         // Send the messages to the Anthropic API and await the model's response
//         const response = await client.messages.create({
//             model: "claude-sonnet-4-6",   // Specify the Claude model to use for generation
//             max_tokens: 1024,              // Cap the response length to 1024 tokens
//             system: "You are a helpful assistant.", // Set the system prompt that defines the AI's persona/behavior
//             messages: messages,            // Pass the full conversation history so the model has context
//         });

//         // Extract text from response — find the first content block of type "text" in the response array
//         const textContent = response.content.find((c) => c.type === "text");

//         // Safely retrieve the text string, defaulting to an empty string if no text block was found
//         const text = textContent ? textContent.text : "";

//         // Return a JSON response shaped as an assistant message, ready for the client to append to the chat
//         return NextResponse.json({
//             role: "assistant", // Identify the sender role so the UI can render it correctly
//             content: text,     // The actual text generated by the AI model
//         });
//     } catch (error) {
//         // If the API call fails for any reason, return a 500 error response with a descriptive message
//         return NextResponse.json(
//             { error: "Failed to generate response" }, // Error payload sent back to the client
//             { status: 500 }                           // HTTP 500 status signals an internal server error
//         );
//     }
// }


//---V2 STREAMING - For real-time streaming responses:----//
// Unlike V1 which waits for the full response, this version streams tokens to the client as they are generated.
// This uses Server-Sent Events (SSE) — a standard protocol for pushing data from server to client over HTTP.


export async function POST(request: NextRequest) {
    // Parse the incoming JSON body and extract the messages array (same as V1)
    const { messages } = await request.json();

    try {
        // Open a streaming connection to the Anthropic API instead of awaiting a full response.
        // `client.messages.stream()` returns an event emitter that fires as tokens arrive.
        const stream = client.messages.stream({
            model: "claude-sonnet-4-6",      // The Claude model to use for generation
            max_tokens: 1024,                 // Maximum tokens the model is allowed to generate
            system: "You are a helpful assistant.", // System prompt defining the AI's behavior
            messages: messages,               // Full conversation history for context
        });

        // TextEncoder converts JavaScript strings into Uint8Array bytes,
        // which is required by the ReadableStream controller to enqueue data chunks.
        const encoder = new TextEncoder();

        // ReadableStream is a Web Streams API object that lets us push data to the client
        // incrementally — each chunk is sent as soon as it's ready, not all at once.
        const readableStream = new ReadableStream({
            // `start` is called immediately when the stream is created.
            // `controller` is used to enqueue (send) data chunks or signal completion/errors.
            async start(controller) {

                // "text" fires each time a new token/text chunk arrives from the model.
                // We encode it as an SSE-formatted message: `data: <json>\n\n`
                // The client reads each `data:` line and extracts the `text` field to display it.
                stream.on("text", (text) => {
                    controller.enqueue(encoder.encode(`data: ${JSON.stringify({ text })}\n\n`));
                });

                // "message" fires once when the model has finished generating the full response.
                // We send a final SSE event with `done: true` and the complete message object,
                // then close the stream so the client knows no more data will arrive.
                stream.on("message", (message) => {
                    controller.enqueue(
                        encoder.encode(`data: ${JSON.stringify({ done: true, message })}\n\n`)
                    );
                    controller.close(); // Signal end-of-stream to the client
                });

                // "error" fires if the Anthropic stream encounters a problem mid-generation.
                // Passing the error to `controller.error()` aborts the ReadableStream
                // and propagates the failure to the client.
                stream.on("error", (error) => {
                    controller.error(error);
                });
            },
        });

        // Return the ReadableStream as the HTTP response body.
        // The headers tell the client this is a live SSE connection:
        return new Response(readableStream, {
            headers: {
                "Content-Type": "text/event-stream", // Signals SSE format — client uses EventSource API to read it
                "Cache-Control": "no-cache",          // Prevents proxies/browsers from caching the stream
                "Connection": "keep-alive",           // Keeps the HTTP connection open for the duration of the stream
            },
        });
    } catch (error) {
        // If stream setup fails before any data is sent, return a plain 500 error response
        return new Response("Error streaming response", { status: 500 });
    }
}